### ISSUE TITLE
[QnA maker]QnAMaker confidence scores going down

### ISSUE THREAD

**Issue by sanjeevgaut** [microsoft/BotBuilder-CognitiveServices#177] opened 2019-06-28 01:01 UTC
Hi

When i check a question in QNA maker, i get very good score and correct response. when i check same question through my code i get very low score.
for example in qna maker i get score as 89 but in my code it get as low as 19 to 20.
I know scores can very from qna but this is huge difference

This is very strange behavior.
Qna KB ID: 2e7c7108-6dfb-4711-8296-743263c96dbe

@microsoft Bot Framework

**Comment by jwiley84** [comment] 2019-06-28 15:39
Closing as this is a duplicate of #176

**Closed by jwiley84** 2019-06-28 15:39 UTC
