### ISSUE TITLE
[Feedback] Let's add comments to code samples to make code self describable. for example Active Learning C# sample

### ISSUE THREAD

**Issue by SychevIgor** [Microsoft/BotBuilder-CognitiveServices#92] opened 2018-03-25 12:23 UTC
Now, without readme file - there is no way to understand how I should use it from source code
Even the dummy comment from readme https://github.com/Microsoft/BotBuilder-CognitiveServices/tree/master/CSharp/Samples/QnAMaker on top of Dialog will help.

Like this:
// "Active learning can be enabled using the QnA Maker dialog by setting the optional parameter 'top' to some value greater than 1"

[Serializable]
    [QnAMaker("set yout subscription key here", "set your kbid here", "I don't understand this right now! Try another query!", 0.50, 3)]
    public class QnADialogWithActiveLearning : QnAMakerDialog
    {
    }

**Comment by SychevIgor** [comment] 2018-10-18 11:03
nobody care

**Comment by CoHealer** [comment] 2018-10-30 21:06
Hey SychevIgor. I apologize that no one has seen this issue until now. I'll forward this to the team and they can look at adding better comments to the sample.

**Comment by CoHealer** [comment] 2018-11-15 00:46
Closing as by design. Readme is intended comment mechanism for the sample.

**Closed by CoHealer** 2018-11-15 00:46 UTC
Labels: Doc Update, bug
