### ISSUE TITLE
Using the nuget package on mac

### ISSUE THREAD

**Issue by fplaten** [Microsoft/BotBuilder-CognitiveServices#102] opened 2018-05-14 14:00 UTC
Hey guys,

I tried using the package on mac, installing it with nuget. It was added as expected to the packages folder but I could not reference it in code because it was not added to the project references. On further inspection I found out that msbuild was not able to find the assembly because the structure of the nuget package was malformed:

![image](https://user-images.githubusercontent.com/6834102/40001753-2bc5df90-578f-11e8-82ad-7ef2905a292a.png)

I manually edited the package structure and file names and it worked as intended:

![image](https://user-images.githubusercontent.com/6834102/40001875-70fd0016-578f-11e8-8357-8402b1de493f.png)

Is that an issue on your end when building the nuget package or is it just not intended to be used on a mac?

CognitiveServices nuget version: 1.1.7
msbuild: 15.6.0.0
nuget: 4.3.0.4406

Thanks for your help :)

**Comment by nodeomega** [comment] 2018-05-15 01:44
This does seem to be an issue with the NuGet package, as I do not see this issue with any other packages at this time.  I was able to replicate and verify this and will be in touch with the package author regarding this issue.

**Comment by JasonSowers** [comment] 2018-07-05 13:30
BotBuilder was not built to be compatible with Mono.   I'm not going to say it would be impossible, but it is not something we actually support.  To build C# bots with the V3 SDK  you would need to do so one a windows machine, partition, or VM.  For the V3 SDK Node.js was intended to be our multi-platform solution.

**Closed** 2018-07-05 13:31 UTC
Labels: .NET SDK
