### ISSUE TITLE
Error in QnA maker sample

### ISSUE THREAD

**Issue by RealLucasMeyer** [Microsoft/BotBuilder-CognitiveServices#53] opened 2017-09-11 20:16 UTC
I did `npm install --save botbuilder-cognitiveservices`
and tried to use this example: `https://github.com/Microsoft/BotBuilder-CognitiveServices/tree/master/Node/samples/QnAMakerSimpleBot`
It fails with - `ERROR: Cannot read property 'length' of undefined
at node_modules\botbuilder-cognitiveservices\lib\QnAMakerRecognizer.js:54:70)`.

It works if I use `var cognitiveservices = require('../../lib/botbuilder-cognitiveservices');` instead of the usual `require('botbuilder-cognitiveservices');`. 

Maybe the version in npm needs to be updated?

**Comment by dasvictor** [comment] 2017-09-13 08:22
I'm closing this as I'm not able to repro this. It works as expected even with the following after installing the npm:
var cognitiveservices = require('botbuilder-cognitiveservices');

Feel free to reopen in case the issue is still there. And let us know the other details like node version, etc. so that we can repro it. Thanks.

**Closed by dasvictor** 2017-09-13 08:22 UTC

**Comment by RealLucasMeyer** [comment] 2017-09-14 00:20
My node version is 8.4.0 but I realized that I only have an error when resultCode != 200.

I think the issue is that the version of QnaMakerRecognizer.js installed after running `npm install --save botbuilder-cognitiveservices`, line 50, reads: 
```
               try {
                    if (!error) {
                        result = JSON.parse(body);
                        var answerEntities = [];
                        if (result.answers !== null && result.answers.length > 0) {
                            result.answers.forEach(function (ans) {
                                ans.score /= 100;
                                ans.answer = htmlentities.decode(ans.answer);
                                var answerEntity = {
                                    score: ans.score,
                                    entity: ans.answer,
                                    type: 'answer'
                                };
 ```
The error happens in line 54, because `result.answers` is undefined.

The code is different in the [GitHub Version](https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/Node/lib/QnAMakerRecognizer.js), that checks for response.statusCode first:

```
              try {
                    if (!error) {
                        if (response.statusCode === 200) {
                            var answerEntities = [];
                            if (result.answers && result.answers.length > 0) {
                                result.answers.forEach(function (ans) {
                                    ans.score /= 100;
                                    ans.answer = htmlentities.decode(ans.answer);
                                    if (ans.questions && ans.questions.length > 0) {
                                        ans.questions = ans.questions.map(function (q) { return htmlentities.decode(q); });
                                    }
                                    var answerEntity = {
                                        score: ans.score,
                                        entity: ans.answer,
                                        type: 'answer'
                                    };
                                    answerEntities.push(answerEntity);
 ```

Should the `github` version that is about one month old be different from the `npm` version?

**Comment by abalbin** [comment] 2018-02-21 23:55
Hi,

any news about this issue? The npm version it's still 1.1.0. I believe that this fix should come with a new version. Is there any release date for this version?

Thanks!
